version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=MyDatabase;User=sa;Password=Password1234;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y  # Acepta el EULA de Microsoft
      - SA_PASSWORD=Password1234  # Define la contraseña para el usuario 'sa' (superusuario)
      - MSSQL_PID=Express  # Define la edición de SQL Server (en este caso, Express)
    ports:
      - "1433:1433"
